// Shared country list for selection and display
export interface CountryInfo {
  code: string;
  name: string;
  nameLocal?: string;
  flag?: string;
}

export const COUNTRIES: CountryInfo[] = [
  { code: "AF", name: "Afghanistan", nameLocal: "افغانستان", flag: "🇦🇫" },
  { code: "AL", name: "Albania", nameLocal: "Shqipëri", flag: "🇦🇱" },
  { code: "DZ", name: "Algeria", nameLocal: "الجزائر", flag: "🇩🇿" },
  { code: "AR", name: "Argentina", nameLocal: "Argentina", flag: "🇦🇷" },
  { code: "AM", name: "Armenia", nameLocal: "Հայաստան", flag: "🇦🇲" },
  { code: "AU", name: "Australia", nameLocal: "Australia", flag: "🇦🇺" },
  { code: "AT", name: "Austria", nameLocal: "Österreich", flag: "🇦🇹" },
  { code: "AZ", name: "Azerbaijan", nameLocal: "Azərbaycan", flag: "🇦🇿" },
  { code: "BH", name: "Bahrain", nameLocal: "البحرين", flag: "🇧🇭" },
  { code: "BD", name: "Bangladesh", nameLocal: "বাংলাদেশ", flag: "🇧🇩" },
  { code: "BY", name: "Belarus", nameLocal: "Беларусь", flag: "🇧🇾" },
  { code: "BE", name: "Belgium", nameLocal: "België", flag: "🇧🇪" },
  { code: "BA", name: "Bosnia", nameLocal: "Bosna", flag: "🇧🇦" },
  { code: "BR", name: "Brazil", nameLocal: "Brasil", flag: "🇧🇷" },
  { code: "BG", name: "Bulgaria", nameLocal: "България", flag: "🇧🇬" },
  { code: "CA", name: "Canada", nameLocal: "Canada", flag: "🇨🇦" },
  { code: "CL", name: "Chile", nameLocal: "Chile", flag: "🇨🇱" },
  { code: "CN", name: "China", nameLocal: "中国", flag: "🇨🇳" },
  { code: "CO", name: "Colombia", nameLocal: "Colombia", flag: "🇨🇴" },
  { code: "HR", name: "Croatia", nameLocal: "Hrvatska", flag: "🇭🇷" },
  { code: "CY", name: "Cyprus", nameLocal: "Κύπρος", flag: "🇨🇾" },
  { code: "CZ", name: "Czechia", nameLocal: "Česko", flag: "🇨🇿" },
  { code: "DK", name: "Denmark", nameLocal: "Danmark", flag: "🇩🇰" },
  { code: "EG", name: "Egypt", nameLocal: "مصر", flag: "🇪🇬" },
  { code: "EE", name: "Estonia", nameLocal: "Eesti", flag: "🇪🇪" },
  { code: "FI", name: "Finland", nameLocal: "Suomi", flag: "🇫🇮" },
  { code: "FR", name: "France", nameLocal: "France", flag: "🇫🇷" },
  { code: "GE", name: "Georgia", nameLocal: "საქართველო", flag: "🇬🇪" },
  { code: "DE", name: "Germany", nameLocal: "Deutschland", flag: "🇩🇪" },
  { code: "GR", name: "Greece", nameLocal: "Ελλάδα", flag: "🇬🇷" },
  { code: "HK", name: "Hong Kong", nameLocal: "香港", flag: "🇭🇰" },
  { code: "HU", name: "Hungary", nameLocal: "Magyarország", flag: "🇭🇺" },
  { code: "IS", name: "Iceland", nameLocal: "Ísland", flag: "🇮🇸" },
  { code: "IN", name: "India", nameLocal: "भारत", flag: "🇮🇳" },
  { code: "ID", name: "Indonesia", nameLocal: "Indonesia", flag: "🇮🇩" },
  { code: "IR", name: "Iran", nameLocal: "ایران", flag: "🇮🇷" },
  { code: "IQ", name: "Iraq", nameLocal: "العراق", flag: "🇮🇶" },
  { code: "IE", name: "Ireland", nameLocal: "Éire", flag: "🇮🇪" },
  { code: "IL", name: "Israel", nameLocal: "ישראל", flag: "🇮🇱" },
  { code: "IT", name: "Italy", nameLocal: "Italia", flag: "🇮🇹" },
  { code: "JP", name: "Japan", nameLocal: "日本", flag: "🇯🇵" },
  { code: "JO", name: "Jordan", nameLocal: "الأردن", flag: "🇯🇴" },
  { code: "KZ", name: "Kazakhstan", nameLocal: "Қазақстан", flag: "🇰🇿" },
  { code: "KE", name: "Kenya", nameLocal: "Kenya", flag: "🇰🇪" },
  { code: "KW", name: "Kuwait", nameLocal: "الكويت", flag: "🇰🇼" },
  { code: "KG", name: "Kyrgyzstan", nameLocal: "Кыргызстан", flag: "🇰🇬" },
  { code: "LV", name: "Latvia", nameLocal: "Latvija", flag: "🇱🇻" },
  { code: "LB", name: "Lebanon", nameLocal: "لبنان", flag: "🇱🇧" },
  { code: "LY", name: "Libya", nameLocal: "ليبيا", flag: "🇱🇾" },
  { code: "LT", name: "Lithuania", nameLocal: "Lietuva", flag: "🇱🇹" },
  { code: "NL", name: "Netherlands", nameLocal: "Nederland", flag: "🇳🇱" },
  { code: "NO", name: "Norway", nameLocal: "Norge", flag: "🇳🇴" },
  { code: "PL", name: "Poland", nameLocal: "Polska", flag: "🇵🇱" },
  { code: "PT", name: "Portugal", nameLocal: "Portugal", flag: "🇵🇹" },
  { code: "QA", name: "Qatar", nameLocal: "قطر", flag: "🇶🇦" },
  { code: "RO", name: "Romania", nameLocal: "România", flag: "🇷🇴" },
  { code: "RU", name: "Russia", nameLocal: "Россия", flag: "🇷🇺" },
  { code: "SA", name: "Saudi Arabia", nameLocal: "السعودية", flag: "🇸🇦" },
  { code: "RS", name: "Serbia", nameLocal: "Србија", flag: "🇷🇸" },
  { code: "SG", name: "Singapore", nameLocal: "Singapore", flag: "🇸🇬" },
  { code: "SK", name: "Slovakia", nameLocal: "Slovensko", flag: "🇸🇰" },
  { code: "SI", name: "Slovenia", nameLocal: "Slovenija", flag: "🇸🇮" },
  { code: "ZA", name: "South Africa", nameLocal: "South Africa", flag: "🇿🇦" },
  { code: "KR", name: "South Korea", nameLocal: "대한민국", flag: "🇰🇷" },
  { code: "ES", name: "Spain", nameLocal: "España", flag: "🇪🇸" },
  { code: "SE", name: "Sweden", nameLocal: "Sverige", flag: "🇸🇪" },
  { code: "CH", name: "Switzerland", nameLocal: "Schweiz", flag: "🇨🇭" },
  { code: "SY", name: "Syria", nameLocal: "سوريا", flag: "🇸🇾" },
  { code: "TW", name: "Taiwan", nameLocal: "台灣", flag: "🇹🇼" },
  { code: "TH", name: "Thailand", nameLocal: "ไทย", flag: "🇹🇭" },
  { code: "TN", name: "Tunisia", nameLocal: "تونس", flag: "🇹🇳" },
  { code: "TR", name: "Türkiye", nameLocal: "Türkiye", flag: "🇹🇷" },
  { code: "UA", name: "Ukraine", nameLocal: "Україна", flag: "🇺🇦" },
  { code: "AE", name: "UAE", nameLocal: "الإمارات", flag: "🇦🇪" },
  { code: "GB", name: "United Kingdom", nameLocal: "UK", flag: "🇬🇧" },
  { code: "US", name: "United States", nameLocal: "USA", flag: "🇺🇸" },
  { code: "UZ", name: "Uzbekistan", nameLocal: "Oʻzbekiston", flag: "🇺🇿" },
  { code: "VN", name: "Vietnam", nameLocal: "Việt Nam", flag: "🇻🇳" },
  { code: "YE", name: "Yemen", nameLocal: "اليمن", flag: "🇾🇪" },
];

export function getCountryNameByCode(code?: string | null): string | undefined {
  if (!code) return undefined;
  const found = COUNTRIES.find(
    (c) => c.code.toUpperCase() === code.toUpperCase(),
  );
  return found?.name;
}
