name: DAST Security Scan

on:
  # Manual trigger only - requires production URL
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL to scan (e.g., https://www.owl-app.com)'
        required: true
        default: 'https://www.owl-app.com'

jobs:
  zap-scan:
    name: OWASP ZAP Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: ${{ github.event.inputs.target_url }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

